name: Ordinary PHP Composer Library Test

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Container
        run: make php-image

      - name: Validate composer.json
        run: make validate-deps

      - name: Cache Composer Dependencies
        id: cache-composer-deps
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Fetch Dependencies
        if: steps.cache-composer-deps.outputs.cache-hit != 'true'
        run: make deps

      - name: PHP Linting
        run: make phplint

      - name: PHP CodeSniffer
        run: make phpcs

      - name: PHP Psalm
        run: make psalm

      - name: PHP Unit Tests
        run: make phpunit
